name: rsync-to-do

on: [push]

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.SSH_KEY}}
          known_hosts: "temp"
      - name: add known hosts
        run: ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
      - name: create .env file
        run: touch .env
      - name: populate .env file
        run: echo WP_DEFAULT_THEME=${{secrets.WP_DEFAULT_THEME}} >> .env
      - name: composer
        run: composer update
      - name: npm install
        run: npm run global-install
      - name: npm build
        run: npm run global-build
      - name: run rsync
        run: rsync -azh --delete ./public ./vendor ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/var/www/html/
